# Generated by Django 5.1.2 on 2024-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biografiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ism')),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
