# Generated by Django 5.1.2 on 2024-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ism')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('bio', models.TextField(verbose_name='info')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ism')),
                ('year', models.CharField(max_length=100, verbose_name='yil')),
                ('info', models.TextField(verbose_name='info')),
            ],
        ),
        migrations.AddField(
            model_name='biografiya',
            name='description',
            field=models.CharField(default=2, max_length=100, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='bio',
            field=models.TextField(verbose_name='info'),
        ),
    ]
