# Generated by Django 5.1.2 on 2024-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_index_biografiya_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografiya',
            name='add',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
    ]
