# Generated by Django 5.1.2 on 2024-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_biografiya_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image',
            field=models.ImageField(default=2, upload_to='images/', verbose_name='rasm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='add',
            field=models.TextField(blank=True, null=True, verbose_name='add'),
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='rasm'),
        ),
    ]
