# Generated by Django 5.1.2 on 2024-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_index_image_alter_add_image_alter_biografiya_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('icon', models.ImageField(upload_to='images/', verbose_name='rasm')),
            ],
        ),
    ]
