# Generated by Django 5.1.2 on 2024-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(default=2, max_length=100, verbose_name='des'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='ism'),
            preserve_default=False,
        ),
    ]
