# Generated by Django 5.1.2 on 2024-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=2, max_length=100, verbose_name='user'),
            preserve_default=False,
        ),
    ]
