# Generated by Django 5.1.2 on 2024-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name': "Qo'shimcha", 'verbose_name_plural': "Qo'shimcha"},
        ),
        migrations.AlterModelOptions(
            name='biografiya',
            options={'verbose_name': 'Batafsil', 'verbose_name_plural': 'Batafsil'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Asosiy sahifa', 'verbose_name_plural': 'Asosiy sahifa'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Web sayt', 'verbose_name_plural': 'Web sayt'},
        ),
        migrations.AddField(
            model_name='site',
            name='page1',
            field=models.CharField(default=2, max_length=100, verbose_name='1-sahifa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='page2',
            field=models.CharField(default=2, max_length=100, verbose_name='2-sahifa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='page3',
            field=models.CharField(default=2, max_length=100, verbose_name='3-sahifa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='page4',
            field=models.CharField(default=1, max_length=100, verbose_name='4-sahifa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add',
            name='bio',
            field=models.TextField(verbose_name="ma'lumot"),
        ),
        migrations.AlterField(
            model_name='add',
            name='description',
            field=models.CharField(max_length=100, verbose_name='qisqacha'),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='add',
            field=models.TextField(blank=True, null=True, verbose_name="qo'shimcha"),
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='bio',
            field=models.TextField(verbose_name="ma'lumot"),
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='description',
            field=models.CharField(max_length=100, verbose_name='qisqacha'),
        ),
        migrations.AlterField(
            model_name='biografiya',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=100, verbose_name='fordalanuvchi'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='izohi'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yuborilgan sana'),
        ),
        migrations.AlterField(
            model_name='index',
            name='info',
            field=models.TextField(verbose_name="ma'lumot"),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='index',
            name='year',
            field=models.CharField(max_length=100, verbose_name='yili'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=100, verbose_name='qisqacha'),
        ),
        migrations.AlterField(
            model_name='site',
            name='icon',
            field=models.ImageField(upload_to='images/', verbose_name='belgisi'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=100, verbose_name='nomi'),
        ),
    ]
