# Generated by Django 5.1.2 on 2024-11-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_add_options_alter_biografiya_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name': '3-sahifa', 'verbose_name_plural': '3-sahifa'},
        ),
        migrations.AlterModelOptions(
            name='biografiya',
            options={'verbose_name': '2-sahifa', 'verbose_name_plural': '2-sahifa'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': '1-sahifa', 'verbose_name_plural': '1-sahifa'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '4-sahifa', 'verbose_name_plural': '4-sahifa'},
        ),
        migrations.AddField(
            model_name='comments',
            name='permission',
            field=models.CharField(default=2, max_length=200, verbose_name='izoh qoldirish uchun'),
            preserve_default=False,
        ),
    ]
