# Generated by Django 5.1.2 on 2024-11-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_comments_permission_site_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Web sayt', 'verbose_name_plural': 'Web sayt'},
        ),
    ]
